test_that("Basic params are saved to environment in default setting", {
  get_param()
  expect_true(exists("date_real", envir = .GlobalEnv))
  expect_true(exists("date_currel", envir = .GlobalEnv))
  expect_true(exists("date_prevrel", envir = .GlobalEnv))
  expect_true(exists("real_year", envir = .GlobalEnv))
  expect_true(exists("real_month_num", envir = .GlobalEnv))
  expect_true(exists("real_month_lab", envir = .GlobalEnv))
  expect_true(exists("currel_year", envir = .GlobalEnv))
  expect_true(exists("currel_month_num", envir = .GlobalEnv))
  expect_true(exists("currel_month_lab", envir = .GlobalEnv))
})

test_that("Basic and extra params are saved to environment when extra == TRUE", {
  get_param(extra = TRUE)
  expect_true(exists("date_real", envir = .GlobalEnv))
  expect_true(exists("date_currel", envir = .GlobalEnv))
  expect_true(exists("date_prevrel", envir = .GlobalEnv))
  expect_true(exists("real_year", envir = .GlobalEnv))
  expect_true(exists("real_month_num", envir = .GlobalEnv))
  expect_true(exists("real_month_lab", envir = .GlobalEnv))
  expect_true(exists("currel_year", envir = .GlobalEnv))
  expect_true(exists("currel_month_num", envir = .GlobalEnv))
  expect_true(exists("currel_month_lab", envir = .GlobalEnv))
  expect_true(exists("PrevMonthNum", envir = .GlobalEnv))
  expect_true(exists("PrevMonthLab", envir = .GlobalEnv))
  expect_true(exists("CurMonthLab", envir = .GlobalEnv))
  expect_true(exists("CurMonth", envir = .GlobalEnv))
  expect_true(exists("CurYear", envir = .GlobalEnv))
  expect_true(exists("PrevYear", envir = .GlobalEnv))
  expect_true(exists("Months", envir = .GlobalEnv))
})

test_that("Output param objects are of appropriate classes", {
  get_param(extra = TRUE)
  expect_true(class(date_real) == "Date")
  expect_true(class(date_currel) == "Date")
  expect_true(class(date_prevrel) == "Date")
  expect_true(is.numeric(real_year))
  expect_true(is.numeric(real_month_num))
  expect_true(is.numeric(currel_year))
  expect_true(is.numeric(currel_month_num))
  expect_true(is.numeric(PrevMonthNum))
  expect_true(is.numeric(CurMonth))
  expect_true(is.numeric(CurYear))
  expect_true(is.numeric(PrevYear))
  expect_true(is.numeric(Months))
  expect_true(is.factor(real_month_lab))
  expect_true(is.factor(currel_month_lab))
  expect_true(is.factor(PrevMonthLab))
  expect_true(is.factor(CurMonthLab))
})
